---
#-------------------------------
# Site Settings
title: Denisa Vostrá
logo:
description: Spisovatelka, která vystudovala japanologii, chemické inženýrství a doktorské studium na divadelní fakultě. S tituly ze značně rozdílných oborů umí každý z nich vidět i zvenčí a umí tak podat pomocnou ruku těm, kdo se teprve nesměle rozhlížejí. Učí studenty univerzity i středoškoláky a často jim dodává odvahu nejen ke studiu japonštiny, ale i k novému pohledu na sebe sama. V současné době přednáší japonskou kulturu a historii a píše knihy, které se vyrovnávají s těžkostmi světa především smíchem a nadhledem.

#-------------------------------
# Author Global Settings
author:
    author__name: Denisa Vostrá
    author__bio: Spisovatelka, která vystudovala japanologii, chemické inženýrství a doktorské studium na divadelní fakultě. S tituly ze značně rozdílných oborů umí každý z nich vidět i zvenčí a umí tak podat pomocnou ruku těm, kdo se teprve nesměle rozhlížejí. Učí studenty univerzity i středoškoláky a často jim dodává odvahu nejen ke studiu japonštiny, ale i k novému pohledu na sebe sama. V současné době přednáší japonskou kulturu a historii a píše knihy, které se vyrovnávají s těžkostmi světa především smíchem a nadhledem.
    author__avatar: /images/authors/dvostra.jpg

#-------------------------------
# Navigation Settings
menu__settings:
    menu__items:
        - title: "Domů"
          url: "/"
        - title: "Životopis"
          url: "/about/"
        - title: "Japonština"
          url: "/japonstina/"
        # - title: "Autoři"
        #   url: "/authors/"

#-------------------------------
# Hero Settings
hero:
    hero__title: "<small><small>4. 9. 2024 vyšla naše kniha <i>Hrom do palice aneb Jak najít svůj život</i>. Mám radost z načasování, na začátku školního roku by knížka mohla být dobrým impulsem (nejen) pro teenager(k)y a jejich rodiče. Nabízí ji Luxor, Kosmas i další knihkupci (i jako e-knihu). Za všechny autory přeju pohodové čtení!</small></small>"

#-------------------------------
# Blog Settings
blog:
    blog__title: Všechny příspěvky
    blog__description:

#-------------------------------
# Recommended Tag Settings
tag:
    enable: false
    tag__title: Recommended
    tag__name: Motivation

#-------------------------------
# Newsletter Settings
mailchimp:
    enable: false
    mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__title: Odběr novinek
    mailchimp__description: Odebírejte novinky od Denisy Vostré, čerstvě pečené přímo do vaší schránky.
    mailchimp__input__text: Email...
    mailchimp__button__text: Odebírat
    mailchimp__background__image: "/images/110.jpg"

#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
    menu__items:
        - title: "Domů"
          url: "/"
        - title: "Životopis"
          url: "/about/"
        - title: "Japonština"
          url: "/japonstina/"
        - title: "Učebnice"
          url: "/japonstina/ucebnice"
        # - title: "Autoři"
        #   url: "/authors/"
        # - title: "Elements"
        #   url: "/elements/"

# Social Links
social:
    - { icon: "", color: "#563ACC", name: Mastodon, link: "https://ohai.social/@denisav" }
    - { icon: "", color: "#E4405F", name: Instagram, link: "https://www.instagram.com/denisa.vostra" }
    - {
          icon: "",
          color: "#ff0000",
          name: Přednášky na Youtube,
          link: "https://www.youtube.com/watch?v=0hCXiOQk0g4&list=PLfCjfwH2L15QpaiDpdWJpOgv600X4sjdW",
      }
    - { icon: "", color: "#E20025", name: Knihy na Kosmas.cz, link: "https://www.kosmas.cz/autor/3262/denisa-vostra/" }
    - { icon: "", color: "#3F2C20", name: Knihy na Goodreads, link: "https://www.goodreads.com/author/show/3394917.Denisa_Vostr_" }
    - {
          icon: "",
          color: "#ff0000",
          name: Knihy v Městské knihovně v Praze,
          link: "https://search.mlp.cz/cz/?p=&query=fql%3Axrank%28%28generic1%3Aint32%28%221386470%22%2C+mode%3D%22or%22%29+and+meta.collection%3Astring%28%22tituly%22%2C+mode%3D%22or%22%29%29+and+not+filter%28nadrizeny%3Astring%28%22HIDDEN%22%2C+mode%3D%22and%22%29%29%2C+ngeneric7%3Astring%28%22P%22%29%2C+ngeneric7%3Astring%28%22D%22%29%2C+boost+%3D+1000%29#/c_s_ol=query-eq:fql%253Axrank%2528%2528generic1%253Aint32%2528%25221386470%2522%252C%2Bmode%253D%2522or%2522%2529%2Band%2Bmeta.collection%253Astring%2528%2522tituly%2522%252C%2Bmode%253D%2522or%2522%2529%2529%2Band%2Bnot%2Bfilter%2528nadrizeny%253Astring%2528%2522HIDDEN%2522%252C%2Bmode%253D%2522and%2522%2529%2529%252C%2Bngeneric7%253Astring%2528%2522P%2522%2529%252C%2Bngeneric7%253Astring%2528%2522D%2522%2529%252C%2Bboost%2B%253D%2B1000%2529-amp:navigation-eq:-amp:sortOrder1-eq:-amp:sortBy1-eq:default-amp:lang-eq:cs",
      }
    - { icon: "", color: "#9E0000", name: ČBDB.cz, link: "https://www.cbdb.cz/autor-12683-denisa-vostra?show=knihy" }
    - { icon: "", color: "#A03A3B", name: Databazeknih.cz, link: "https://www.databazeknih.cz/vydane-knihy/denisa-vostra-29327" }
    - { icon: "", color: "#1852B1", name: Blog na Aktuálně.cz, link: "https://blog.aktualne.cz/blogy/denisa-vostra.php" }

#-------------------------------
# Contact Settings
contact:
    email:

# NOTE
# Dann theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus:
    enable: false
    disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
